version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 888276918709.dkr.ecr.ap-south-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 888276918709.dkr.ecr.ap-south-1.amazonaws.com/simple:latest .
      - docker tag 888276918709.dkr.ecr.ap-south-1.amazonaws.com/simple:latest 888276918709.dkr.ecr.ap-south-1.amazonaws.com/simple:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 888276918709.dkr.ecr.ap-south-1.amazonaws.com/simple:latest .
      
artifacts:
    files: imagedefinitions.json
